/** LATAM / immigrant Monday blog refill. INSERT OR IGNORE so runtime backfill is idempotent. */
export const BLOG_TOPIC_QUEUE_LATAM_SEED_SQL = `
INSERT OR IGNORE INTO blog_topic_queue (id, slug, title, angle, cluster, status, sort_order, created_at) VALUES
('btq_25', 'how-to-complete-i-9-section-1-online', 'How to complete I-9 Section 1 online',
 'Audience: new US hires arriving from Spanish LATAM. Official USCIS Form I-9 (Edition 01/20/25) Section 1 only. Honest: Docracy signs the PDF; no List A/B/C inspection, no E-Verify, signing is not work authorization. Steps + FAQ. Link /i-9 and /packets/latam-to-us. Not legal advice.',
 'Employment', 'queued', 250, '2026-09-05T00:00:00.000Z'),
('btq_26', 'apostille-vs-legalization-latam-to-us', 'Apostille vs legalization for LATAM documents used in the US',
 'Audience: people moving MX/CO/PE/etc to the US. What Apostille Convention does, who stamps in origin (SRE, Cancillería, MINEX — official .gob links only, do not invent URLs). Cuba is NOT a party — MINJUS legalization. Docracy does not apostille. Pair with signed POA / constancia. FAQ. Not legal advice.',
 'LATAM', 'queued', 260, '2026-09-05T00:00:00.000Z'),
('btq_27', 'how-to-send-a-cobro-after-esign', 'How to send a cobro after someone signs',
 'Audience: LATAM freelancers who still invoice in MXN/COP/USD. Cobro = paste your Mercado Pago / PayPal / Stripe Payment Link. Docracy never takes the money. Paid is USD $10/month subscription, not MXN billing. No Stripe Connect. Steps + FAQ.',
 'Freelancer', 'queued', 270, '2026-09-05T00:00:00.000Z'),
('btq_28', 'what-is-a-constancia-for-a-us-landlord', 'What is a constancia for a US landlord?',
 'Audience: newcomers without a W-2. Constancia is a signed income note / vault URL, not SAT CSF, not DIAN, not a W-2. How Docracy paid vault share works. Link /income-proof and immigrant housing. FAQ. Not tax advice.',
 'Real Estate', 'queued', 280, '2026-09-05T00:00:00.000Z'),
('btq_29', 'itin-vs-ssn-after-arriving-in-the-us', 'ITIN vs SSN after arriving in the US',
 'Audience: people who cannot get an SSN yet. Official IRS ITIN / W-7 about page and SSA SSN page. Honest: Docracy does not file W-7 or retrieve I-94. We sign I-9 and supporting docs. Link /itin and /after-arrival. FAQ. Not tax advice. Do not invent a W-7 template.',
 'Signing', 'queued', 290, '2026-09-05T00:00:00.000Z'),
('btq_30', 'mexico-sre-apostille-and-us-i-9', 'Mexico SRE apostille and a US I-9 are different jobs',
 'Audience: Mexico → US. SRE apostille (official gob.mx/sre URL) vs signing official I-9 here. Gestorías bundle them; we do not. $10/month subscription includes the LATAM packet + vault. Link /mexico-to-us. FAQ.',
 'LATAM', 'queued', 300, '2026-09-05T00:00:00.000Z'),
('btq_31', 'keep-signed-pdfs-past-9-days', 'How to keep signed PDFs past 9 days',
 'Audience: free-tier senders. 9-day TTL vs paid vault (later of 13 months or next April 15). Signing stays free. LATAM use: I-9 + constancia when a landlord or employer asks again. FAQ. Soft CTA to $10/month.',
 'Signing', 'queued', 310, '2026-09-05T00:00:00.000Z'),
('btq_32', 'after-arrival-i-94-address-change-i-9', 'After arrival: I-94, address change, and day-one I-9',
 'Audience: people who just entered. Official I-94 CBP, USCIS myaccount, address change. We do not retrieve I-94 or file AR-11. We do sign I-9. Link /after-arrival. FAQ. Not immigration advice.',
 'LATAM', 'queued', 320, '2026-09-05T00:00:00.000Z'),
('btq_33', 'roommate-agreement-without-a-w2', 'Roommate agreement when you do not have a W-2',
 'Audience: immigrants sharing a first US apartment. Written rent split vs landlord W-2 demand. Constancia is not a W-2. Free roommate template + paid constancia URL. Link immigrant housing. FAQ. Not legal advice.',
 'Real Estate', 'queued', 330, '2026-09-05T00:00:00.000Z'),
('btq_34', 'spanish-esignature-for-latam-senders', 'Spanish e-signature for LATAM senders (no Portuguese yet)',
 'Audience: Spanish-speaking senders. Locale es, tú-form, signer emails in Spanish. Honest: no Brazilian Portuguese product — Brazil would need a third locale + CNJ e-Apostila, not a Spanish country page. FAQ + CTA to /es.',
 'Signing', 'queued', 340, '2026-09-05T00:00:00.000Z'),
('btq_35', 'colombia-cancilleria-apostille-and-us-i-9', 'Colombia Cancillería apostille vs signing a US I-9',
 'Audience: Colombia → US. Official cancilleria.gov.co apostille/legalización. Siigo/gestorías own search; we sign I-9 and extras. $10/month includes packet + vault. Link /colombia-to-us. FAQ.',
 'LATAM', 'queued', 350, '2026-09-05T00:00:00.000Z'),
('btq_36', 'do-you-need-an-apostille-to-sign-an-i-9', 'Do you need an apostille to sign Form I-9?',
 'Audience: confused first-week hires. I-9 is a USCIS PDF signed in the US; apostille is an origin-country stamp on a public document. Do not mix them. Docracy signs I-9, does not apostille. FAQ. Not legal advice.',
 'Employment', 'queued', 360, '2026-09-05T00:00:00.000Z'),
('btq_37', 'acta-de-nacimiento-apostilla-mexico', 'Acta de nacimiento apostilla: Registro Civil then SRE',
 'Search phrase: acta de nacimiento apostilla / acta México. Step 1 official: https://www.miregistrocivil.gob.mx/ (gob.mx moved new actas here 1 Aug 2025). Step 2 official: https://www.gob.mx/sre/acciones-y-programas/apostilla-y-legalizacion-de-documentos (SRE stamps; we do not). Link /acta and /mexico-to-us. Honest: Docracy signs POA / I-9 / constancia; we do not issue actas or apostille. $10/month keeps the signed extras. FAQ. Not legal advice.',
 'LATAM', 'queued', 370, '2026-09-05T12:00:00.000Z'),
('btq_38', 'cita-consular-ais-cas-ustraveldocs', 'Cita consular AIS / CAS / ustraveldocs — we do not book it',
 'Search phrase: cita consular AIS. Official: https://ais.usvisa-info.com/ (country path chosen on that site). CEAC DS-160 is https://ceac.state.gov/genniv/. Link /consular-appointment. Honest: we do not buy, hold, or reschedule a slot. We sign supporting PDFs (offer, I-9, POA). $10/month vault. FAQ. Not immigration advice.',
 'LATAM', 'queued', 380, '2026-09-05T12:00:00.000Z'),
('btq_39', 'permiso-de-trabajo-i-765-ead-tps', 'Permiso de trabajo I-765 / EAD / TPS — you file, we do not',
 'Search phrase: permiso de trabajo I-765. Official I-765: https://www.uscis.gov/i-765. TPS: https://www.uscis.gov/humanitarian/temporary-protected-status. I-821: https://www.uscis.gov/i-821. Link /ead-tps. Honest: signing ≠ work authorization; no E-Verify; we do not grant TPS or parole. Pair with I-9 we do sign. FAQ. Not legal advice.',
 'Employment', 'queued', 390, '2026-09-05T12:00:00.000Z'),
('btq_40', 'abrir-cuenta-bancaria-con-itin', 'Abrir cuenta with an ITIN: chip first, then the bank',
 'Search phrase: abrir cuenta ITIN. Official ITIN: https://www.irs.gov/tin/itin/how-to-apply-for-an-itin. Bank basics: https://www.consumerfinance.gov/consumer-tools/educator-tools/adult-financial-education/. Link /phone-and-bank and /itin. Honest: we do not sell eSIMs, open accounts, or file W-7. We sign I-9 and a constancia the bank may still reject. FAQ. Not tax or banking advice.',
 'LATAM', 'queued', 400, '2026-09-05T12:00:00.000Z'),
('btq_41', 'apostilla-acta-colombia-cancilleria', 'Colombia acta + Cancillería apostille vs a US I-9',
 'Search phrase: apostilla Colombia / acta Colombia. Official: https://www.cancilleria.gov.co/tramites_servicios/apostilla_legalizacion. Link /colombia-to-us and /acta. Cita consular is AIS, not Cancillería — do not mix. We do not apostille. $10/month packet + vault. FAQ.',
 'LATAM', 'queued', 410, '2026-09-05T12:00:00.000Z'),
('btq_42', 'ds-160-ceac-after-ais-appointment', 'DS-160 on CEAC after you book AIS',
 'Audience: people who typed cita consular then DS-160. Official CEAC: https://ceac.state.gov/genniv/. AIS: https://ais.usvisa-info.com/. Link /consular-appointment. We do not submit DS-160. Supporting docs we sign. FAQ. Not immigration advice.',
 'LATAM', 'queued', 420, '2026-09-05T12:00:00.000Z'),
('btq_43', 'i-9-same-week-as-your-acta-apostille', 'I-9 the same week as your acta apostille — two different jobs',
 'Audience: first-week hires still chasing Registro Civil / SRE. I-9 official: https://www.uscis.gov/i-9. Acta/apostille is origin .gob. Link /i-9 and /acta. Do not wait to sign Section 1. We sign I-9; we do not apostille. FAQ.',
 'Employment', 'queued', 430, '2026-09-05T12:00:00.000Z'),
('btq_44', 'esim-then-itin-then-the-bank', 'eSIM, then ITIN, then the bank (we sell none of these)',
 'Search phrase: chip y banco / abrir cuenta. One-liner: chip first, then the bank. Official CFPB + IRS ITIN links only. Link /phone-and-bank. We do not sell SIMs or open accounts. Soft CTA: $10/month keeps the I-9 and constancia when the bank asks again. FAQ.',
 'LATAM', 'queued', 440, '2026-09-05T12:00:00.000Z');
`;
