/** Seed copied from migrations/0026_template_topic_queue.sql (INSERT OR IGNORE so runtime backfill is idempotent). */
export const TEMPLATE_TOPIC_QUEUE_SEED_SQL = `
INSERT OR IGNORE INTO template_topic_queue (id, slug, title, category, angle, status, sort_order, created_at) VALUES
-- Real Estate (10)
('ttq_001', 'residential-lease-addendum', 'Residential Lease Addendum', 'Real Estate',
 '2 signers: Landlord, Tenant. Short addendum amending an existing residential lease. Placeholders: [Landlord Name], [Tenant Name], [Property Address], [Original Lease Date], [Amendment Summary], [Effective Date]. Clauses: purpose of amendment, what changes, rest of lease unchanged, signatures.',
 'queued', 10, '2026-08-25T00:00:00.000Z'),
('ttq_002', 'commercial-lease-summary', 'Commercial Lease Summary Sheet', 'Real Estate',
 '2 signers: Landlord, Tenant. One-page commercial lease key-terms summary for e-sign confirmation. Placeholders for premises, term, rent, security deposit, permitted use. Not a full lease — acknowledgment of key commercial terms.',
 'queued', 20, '2026-08-25T00:00:00.000Z'),
('ttq_003', 'roommate-expense-agreement', 'Roommate Expense Sharing Agreement', 'Real Estate',
 '2 signers: Roommate A, Roommate B. Split rent/utilities/chores. Placeholders for address, shares, due dates. Termination and dispute basics.',
 'queued', 30, '2026-08-25T00:00:00.000Z'),
('ttq_004', 'parking-space-license', 'Parking Space License Agreement', 'Real Estate',
 '2 signers: Licensor, Licensee. License (not lease) for one parking space. Fee, hours, liability, termination.',
 'queued', 40, '2026-08-25T00:00:00.000Z'),
('ttq_005', 'property-access-acknowledgment', 'Property Access Acknowledgment', 'Real Estate',
 '2 signers: Owner, Visitor/Contractor. Temporary access for inspection or work. Hours, insurance, no tenancy created.',
 'queued', 50, '2026-08-25T00:00:00.000Z'),
('ttq_006', 'short-term-stay-agreement', 'Short-Term Stay Agreement', 'Real Estate',
 '2 signers: Host, Guest. Vacation/short stay (under 30 days). Dates, fee, house rules, damage deposit, cancellation.',
 'queued', 60, '2026-08-25T00:00:00.000Z'),
('ttq_007', 'landlord-reference-letter', 'Landlord Reference Letter', 'Real Estate',
 '1–2 signers: Landlord (required), optional Tenant acknowledgment. Positive rental history reference. Tenancy dates, rent paid, property care.',
 'queued', 70, '2026-08-25T00:00:00.000Z'),
('ttq_008', 'lease-renewal-notice', 'Lease Renewal Offer', 'Real Estate',
 '2 signers: Landlord, Tenant. Offer to renew residential lease at stated terms. New rent, term, deadline to accept.',
 'queued', 80, '2026-08-25T00:00:00.000Z'),
('ttq_009', 'move-out-condition-checklist', 'Move-Out Condition Checklist', 'Real Estate',
 '2 signers: Landlord, Tenant. Room-by-room condition at move-out for deposit purposes. Placeholders for property and date.',
 'queued', 90, '2026-08-25T00:00:00.000Z'),
('ttq_010', 'sublease-consent-letter', 'Landlord Consent to Sublease', 'Real Estate',
 '2–3 signers: Landlord, Original Tenant, Subtenant. Written consent to sublease under existing lease. Conditions and liability.',
 'queued', 100, '2026-08-25T00:00:00.000Z'),

-- Will (8)
('ttq_011', 'simple-will-checklist-acknowledgment', 'Simple Will Preparation Checklist Acknowledgment', 'Will',
 '1 signer: Testator. Acknowledgment they reviewed a checklist of decisions before drafting a will (not the will itself). Disclaimer: not legal advice.',
 'queued', 110, '2026-08-25T00:00:00.000Z'),
('ttq_012', 'funeral-wishes-memorandum', 'Funeral Wishes Memorandum', 'Will',
 '1 signer: Declarant. Non-binding memorandum of funeral/burial wishes for family. Distinct from a will. Placeholders for preferences.',
 'queued', 120, '2026-08-25T00:00:00.000Z'),
('ttq_013', 'personal-property-memorandum', 'Personal Property Memorandum', 'Will',
 '1 signer: Owner. List of tangible personal property gifts to name with a will. State it may be referenced by a will. Placeholders for items and recipients.',
 'queued', 130, '2026-08-25T00:00:00.000Z'),
('ttq_014', 'guardian-nomination-form', 'Guardian Nomination for Minor Children', 'Will',
 '1–2 signers: Parent(s). Nominate guardian if both parents deceased. Not a full will — nomination only. Disclaimer.',
 'queued', 140, '2026-08-25T00:00:00.000Z'),
('ttq_015', 'estate-inventory-worksheet', 'Estate Inventory Worksheet Acknowledgment', 'Will',
 '1 signer. Signed acknowledgment of an attached asset/liability inventory worksheet used for estate planning prep.',
 'queued', 150, '2026-08-25T00:00:00.000Z'),
('ttq_016', 'beneficiary-designation-confirm', 'Beneficiary Designation Confirmation', 'Will',
 '1–2 signers. Confirm beneficiary choices for a named account/policy (high-level; not broker-specific). Placeholders for account and beneficiaries.',
 'queued', 160, '2026-08-25T00:00:00.000Z'),
('ttq_017', 'digital-asset-inventory', 'Digital Asset Inventory Acknowledgment', 'Will',
 '1 signer. Inventory of digital accounts/assets for estate purposes (usernames only, no passwords in doc). Instructions for executor.',
 'queued', 170, '2026-08-25T00:00:00.000Z'),
('ttq_018', 'pet-care-directive', 'Pet Care Directive', 'Will',
 '1–2 signers: Owner, Caregiver. Who cares for pets and funding note. Can accompany a will.',
 'queued', 180, '2026-08-25T00:00:00.000Z'),

-- Power of Attorney (8)
('ttq_019', 'limited-financial-poa', 'Limited Financial Power of Attorney', 'Power of Attorney',
 '2 signers: Principal, Agent. Narrow financial POA for a specific transaction/period. Placeholders for scope and end date. Not legal advice.',
 'queued', 190, '2026-08-25T00:00:00.000Z'),
('ttq_020', 'medical-info-release-poa', 'Medical Information Release Authorization', 'Power of Attorney',
 '1–2 signers: Patient, optional Proxy. Authorize named person to receive medical information. HIPAA-style plain language, US general.',
 'queued', 200, '2026-08-25T00:00:00.000Z'),
('ttq_021', 'child-travel-consent', 'Child Travel Consent Letter', 'Power of Attorney',
 '1–2 signers: Parent/Guardian. Consent for minor to travel with named adult. Dates, destinations, emergency contacts.',
 'queued', 210, '2026-08-25T00:00:00.000Z'),
('ttq_022', 'vehicle-title-poa', 'Vehicle Title Power of Attorney', 'Power of Attorney',
 '2 signers: Owner, Agent. Limited POA to sign DMV/title paperwork for one vehicle. VIN, dates.',
 'queued', 220, '2026-08-25T00:00:00.000Z'),
('ttq_023', 'tax-prep-authorization', 'Tax Preparer Authorization Letter', 'Power of Attorney',
 '2 signers: Taxpayer, Preparer. Authorize preparer to discuss return with tax authority (general letter, not IRS 2848 facsimile).',
 'queued', 230, '2026-08-25T00:00:00.000Z'),
('ttq_024', 'banking-inquiry-authorization', 'Banking Inquiry Authorization', 'Power of Attorney',
 '2 signers: Account Holder, Authorized Person. Allow inquiries (not withdrawals) on a named account for a period.',
 'queued', 240, '2026-08-25T00:00:00.000Z'),
('ttq_025', 'real-estate-closing-poa', 'Real Estate Closing Power of Attorney', 'Power of Attorney',
 '2 signers: Principal, Agent. Limited POA for one property closing. Address, closing date window.',
 'queued', 250, '2026-08-25T00:00:00.000Z'),
('ttq_026', 'revocation-of-poa', 'Revocation of Power of Attorney', 'Power of Attorney',
 '1 signer: Principal. Revoke a prior POA dated [Date] naming [Agent]. Notice language.',
 'queued', 260, '2026-08-25T00:00:00.000Z'),

-- Personal Property (8)
('ttq_027', 'equipment-rental-short', 'Short Equipment Rental Agreement', 'Personal Property',
 '2 signers: Owner, Renter. Camera/tool/equipment rental. Item list, fee, damage, return date.',
 'queued', 270, '2026-08-25T00:00:00.000Z'),
('ttq_028', 'personal-loan-receipt', 'Personal Loan Receipt', 'Personal Property',
 '2 signers: Lender, Borrower. Simple IOU/receipt for a personal loan. Amount, due date, no interest or stated interest.',
 'queued', 280, '2026-08-25T00:00:00.000Z'),
('ttq_029', 'item-loan-agreement', 'Personal Item Loan Agreement', 'Personal Property',
 '2 signers. Borrow a named item (bike, tool, instrument). Care standard, return date, loss liability.',
 'queued', 290, '2026-08-25T00:00:00.000Z'),
('ttq_030', 'storage-unit-access', 'Shared Storage Access Agreement', 'Personal Property',
 '2 signers. Shared storage unit access rules, keys, contents ownership.',
 'queued', 300, '2026-08-25T00:00:00.000Z'),
('ttq_031', 'gift-deed-personal-property', 'Gift of Personal Property Acknowledgment', 'Personal Property',
 '2 signers: Donor, Recipient. Irrevocable gift of described tangible property. No warranties.',
 'queued', 310, '2026-08-25T00:00:00.000Z'),
('ttq_032', 'vehicle-bill-of-sale-simple', 'Simple Vehicle Bill of Sale', 'Personal Property',
 '2 signers: Seller, Buyer. As-is vehicle sale. VIN, price, odometer acknowledgment. Not a title.',
 'queued', 320, '2026-08-25T00:00:00.000Z'),
('ttq_033', 'consignment-goods-agreement', 'Consignment of Goods Agreement', 'Personal Property',
 '2 signers: Consignor, Consignee. Sell goods on consignment. Commission, pricing, unsold return.',
 'queued', 330, '2026-08-25T00:00:00.000Z'),
('ttq_034', 'found-property-receipt', 'Found Property Receipt', 'Personal Property',
 '2 signers: Finder, Owner/Authority. Receipt for returning found property.',
 'queued', 340, '2026-08-25T00:00:00.000Z'),

-- Non-Disclosure (8)
('ttq_035', 'one-way-nda-interview', 'One-Way Interview NDA', 'Non-Disclosure',
 '2 signers: Company, Candidate. Short one-way NDA for job interviews. Narrow confidential info, short term.',
 'queued', 350, '2026-08-25T00:00:00.000Z'),
('ttq_036', 'mutual-nda-partnership', 'Mutual NDA for Partnership Talks', 'Non-Disclosure',
 '2 signers. Mutual NDA for exploring a partnership/JV. 1–2 year term, standard exclusions.',
 'queued', 360, '2026-08-25T00:00:00.000Z'),
('ttq_037', 'vendor-nda-short', 'Short Vendor NDA', 'Non-Disclosure',
 '2 signers: Customer, Vendor. Vendor receives customer confidential info. Return/destroy on end.',
 'queued', 370, '2026-08-25T00:00:00.000Z'),
('ttq_038', 'nda-amendment', 'NDA Amendment', 'Non-Disclosure',
 '2 signers. Amend an existing NDA dated [Date]. What changes; rest remains.',
 'queued', 380, '2026-08-25T00:00:00.000Z'),
('ttq_039', 'residual-knowledge-carveout-ack', 'Residuals Clause Acknowledgment', 'Non-Disclosure',
 '2 signers. Short addendum acknowledging unaided residual knowledge carve-out to an NDA.',
 'queued', 390, '2026-08-25T00:00:00.000Z'),
('ttq_040', 'beta-tester-nda', 'Beta Tester NDA', 'Non-Disclosure',
 '2 signers: Company, Tester. NDA + feedback license for beta software. No compensation unless stated.',
 'queued', 400, '2026-08-25T00:00:00.000Z'),
('ttq_041', 'board-observer-nda', 'Board Observer Confidentiality Agreement', 'Non-Disclosure',
 '2 signers: Company, Observer. Confidentiality for board observer materials.',
 'queued', 410, '2026-08-25T00:00:00.000Z'),
('ttq_042', 'exit-interview-confidentiality', 'Exit Interview Confidentiality Reminder', 'Non-Disclosure',
 '2 signers: Company, Departing Employee. Reminder of ongoing confidentiality / return of property.',
 'queued', 420, '2026-08-25T00:00:00.000Z'),

-- Employment (10)
('ttq_043', 'offer-letter-at-will', 'At-Will Employment Offer Letter', 'Employment',
 '2 signers: Employer, Candidate. Simple at-will offer: title, start date, pay, at-will status. US general; not legal advice.',
 'queued', 430, '2026-08-25T00:00:00.000Z'),
('ttq_044', 'internship-agreement', 'Unpaid Internship Acknowledgment', 'Employment',
 '2 signers: Organization, Intern. Educational internship terms, no employment guarantee. Compliance disclaimer.',
 'queued', 440, '2026-08-25T00:00:00.000Z'),
('ttq_045', 'remote-work-policy-ack', 'Remote Work Policy Acknowledgment', 'Employment',
 '1–2 signers: Employee (required), optional Employer. Acknowledge remote work policy attachment.',
 'queued', 450, '2026-08-25T00:00:00.000Z'),
('ttq_046', 'equipment-return-agreement', 'Employee Equipment Return Agreement', 'Employment',
 '2 signers. List of company equipment to return on separation. Due date, condition.',
 'queued', 460, '2026-08-25T00:00:00.000Z'),
('ttq_047', 'commission-plan-ack', 'Sales Commission Plan Acknowledgment', 'Employment',
 '2 signers: Employer, Salesperson. Acknowledge commission plan summary. Plan may change with notice.',
 'queued', 470, '2026-08-25T00:00:00.000Z'),
('ttq_048', 'background-check-auth', 'Background Check Authorization', 'Employment',
 '1 signer: Applicant. Authorize background check for employment. FCRA-style plain language disclaimer.',
 'queued', 480, '2026-08-25T00:00:00.000Z'),
('ttq_049', 'handbook-acknowledgment', 'Employee Handbook Acknowledgment', 'Employment',
 '1–2 signers: Employee. Received handbook; at-will if applicable; policies may change.',
 'queued', 490, '2026-08-25T00:00:00.000Z'),
('ttq_050', 'probationary-period-ack', 'Probationary Period Acknowledgment', 'Employment',
 '2 signers. Confirm probation length and evaluation criteria. Not a guarantee of continued employment.',
 'queued', 500, '2026-08-25T00:00:00.000Z'),
('ttq_051', 'moonlighting-disclosure', 'Outside Employment Disclosure', 'Employment',
 '2 signers. Employee discloses other jobs; employer consent/conflict rules.',
 'queued', 510, '2026-08-25T00:00:00.000Z'),
('ttq_052', 'separation-agreement-simple', 'Simple Separation Acknowledgment', 'Employment',
 '2 signers. Confirm last day, final pay timing, return of property. Not a full release of claims unless stated briefly with disclaimer.',
 'queued', 520, '2026-08-25T00:00:00.000Z'),

-- Sale and Purchase (8)
('ttq_053', 'goods-purchase-order-ack', 'Purchase Order Acknowledgment', 'Sale and Purchase',
 '2 signers: Buyer, Seller. Acknowledge PO number, items, price, delivery date.',
 'queued', 530, '2026-08-25T00:00:00.000Z'),
('ttq_054', 'as-is-sale-acknowledgment', 'As-Is Sale Acknowledgment', 'Sale and Purchase',
 '2 signers. Buyer accepts goods as-is with inspection opportunity noted.',
 'queued', 540, '2026-08-25T00:00:00.000Z'),
('ttq_055', 'deposit-receipt-sale', 'Sale Deposit Receipt', 'Sale and Purchase',
 '2 signers. Receipt for deposit toward purchase of [Item]. Refundable vs applied terms.',
 'queued', 550, '2026-08-25T00:00:00.000Z'),
('ttq_056', 'supply-terms-short', 'Short Supply Terms Confirmation', 'Sale and Purchase',
 '2 signers. Confirm Incoterms-lite: delivery, payment net days, warranty period.',
 'queued', 560, '2026-08-25T00:00:00.000Z'),
('ttq_057', 'return-merchandise-auth', 'Return Merchandise Authorization', 'Sale and Purchase',
 '2 signers. RMA for return of goods. Condition, refund/credit, restocking fee.',
 'queued', 570, '2026-08-25T00:00:00.000Z'),
('ttq_058', 'auction-bid-acknowledgment', 'Auction Bid Acknowledgment', 'Sale and Purchase',
 '2 signers: Auctioneer/Seller, Bidder. Confirm winning bid and payment deadline.',
 'queued', 580, '2026-08-25T00:00:00.000Z'),
('ttq_059', 'bulk-goods-sale', 'Bulk Goods Sale Agreement', 'Sale and Purchase',
 '2 signers. Sale of quantity of fungible goods. Specs, price, delivery, risk of loss.',
 'queued', 590, '2026-08-25T00:00:00.000Z'),
('ttq_060', 'layaway-agreement', 'Layaway Purchase Agreement', 'Sale and Purchase',
 '2 signers. Layaway schedule for retail goods. Forfeiture rules if abandoned.',
 'queued', 600, '2026-08-25T00:00:00.000Z'),

-- Consulting (10) — historically huge on docracy.com (web design, photography, freelance)
('ttq_061', 'web-design-proposal-ack', 'Web Design Proposal Acknowledgment', 'Consulting',
 '2 signers: Designer, Client. Acknowledge accepted proposal for website design. Scope summary, fee, timeline. IP to client on full payment.',
 'queued', 610, '2026-08-25T00:00:00.000Z'),
('ttq_062', 'web-development-change-order', 'Web Development Change Order', 'Consulting',
 '2 signers. Change order amending scope/fee/timeline of an existing web project.',
 'queued', 620, '2026-08-25T00:00:00.000Z'),
('ttq_063', 'photography-session-contract', 'Photography Session Contract', 'Consulting',
 '2 signers: Photographer, Client. Session date, fee, deliverables count, usage license, cancellation.',
 'queued', 630, '2026-08-25T00:00:00.000Z'),
('ttq_064', 'wedding-photography-addendum', 'Wedding Photography Timeline Addendum', 'Consulting',
 '2 signers. Timeline and shot-list addendum to a wedding photography contract.',
 'queued', 640, '2026-08-25T00:00:00.000Z'),
('ttq_065', 'model-release-short', 'Short Model Release', 'Consulting',
 '2 signers: Model, Photographer/Producer. Permission to use images. Consideration, territory, duration.',
 'queued', 650, '2026-08-25T00:00:00.000Z'),
('ttq_066', 'freelance-retainer-ack', 'Freelance Retainer Acknowledgment', 'Consulting',
 '2 signers: Freelancer, Client. Monthly retainer hours, rollover rules, rate for overage.',
 'queued', 660, '2026-08-25T00:00:00.000Z'),
('ttq_067', 'creative-services-sow', 'Creative Services Statement of Work', 'Consulting',
 '2 signers. SOW for branding/design package. Deliverables, milestones, acceptance.',
 'queued', 670, '2026-08-25T00:00:00.000Z'),
('ttq_068', 'marketing-agency-insertion', 'Marketing Insertion Order', 'Consulting',
 '2 signers: Agency, Client. Insertion order for a campaign flight. Budget, channels, dates.',
 'queued', 680, '2026-08-25T00:00:00.000Z'),
('ttq_069', 'independent-contractor-short', 'Short Independent Contractor Agreement', 'Consulting',
 '2 signers: Client, Contractor. IC status, scope, pay, IP assignment, confidentiality. US general disclaimer.',
 'queued', 690, '2026-08-25T00:00:00.000Z'),
('ttq_070', 'consulting-expense-policy', 'Consulting Expense Reimbursement Terms', 'Consulting',
 '2 signers. What expenses are reimbursable, caps, receipt rules.',
 'queued', 700, '2026-08-25T00:00:00.000Z'),

-- Incorporation (8)
('ttq_071', 'founder-roles-acknowledgment', 'Founder Roles Acknowledgment', 'Incorporation',
 '2–3 signers: Founders. Who does what pre-incorporation. Not a full founders agreement — roles only.',
 'queued', 710, '2026-08-25T00:00:00.000Z'),
('ttq_072', 'board-consent-written', 'Written Consent of Directors (Simple)', 'Incorporation',
 '1+ signers: Directors. Written consent approving a named resolution. Corporate formalities disclaimer.',
 'queued', 720, '2026-08-25T00:00:00.000Z'),
('ttq_073', 'llc-membership-interest-transfer', 'LLC Membership Interest Transfer Consent', 'Incorporation',
 '2+ signers. Consent to transfer membership interest under an operating agreement.',
 'queued', 730, '2026-08-25T00:00:00.000Z'),
('ttq_074', 'corporate-secretary-certificate', 'Secretary Certificate of Incumbency', 'Incorporation',
 '1 signer: Secretary. Certify officers/directors as of a date.',
 'queued', 740, '2026-08-25T00:00:00.000Z'),
('ttq_075', 'dba-registration-ack', 'Assumed Name / DBA Acknowledgment', 'Incorporation',
 '1–2 signers. Internal acknowledgment of DBA use and banking name.',
 'queued', 750, '2026-08-25T00:00:00.000Z'),
('ttq_076', 'shareholder-loan-ack', 'Shareholder Loan Acknowledgment', 'Incorporation',
 '2 signers: Company, Shareholder. Acknowledge loan to/from company. Amount, due date.',
 'queued', 760, '2026-08-25T00:00:00.000Z'),
('ttq_077', 'annual-meeting-minutes-short', 'Short Annual Meeting Minutes', 'Incorporation',
 '1 signer: Chair/Secretary. Minimal annual meeting minutes template for small corp.',
 'queued', 770, '2026-08-25T00:00:00.000Z'),
('ttq_078', 'authorized-signatory-list', 'Authorized Signatory List', 'Incorporation',
 '1–2 signers. Who may bind the company for contracts under a dollar threshold.',
 'queued', 780, '2026-08-25T00:00:00.000Z'),

-- Funding (8)
('ttq_079', 'safe-side-letter-ack', 'Investment Side Letter Acknowledgment', 'Funding',
 '2 signers: Company, Investor. Acknowledge side letter points to a financing (high-level; not a SAFE form).',
 'queued', 790, '2026-08-25T00:00:00.000Z'),
('ttq_080', 'convertible-note-extension', 'Convertible Note Extension', 'Funding',
 '2 signers. Extend maturity of a convertible note. New date, otherwise unchanged.',
 'queued', 800, '2026-08-25T00:00:00.000Z'),
('ttq_081', 'investor-update-nda', 'Investor Update Confidentiality', 'Funding',
 '2 signers. Investor agrees updates are confidential.',
 'queued', 810, '2026-08-25T00:00:00.000Z'),
('ttq_082', 'bridge-loan-term-sheet-ack', 'Bridge Loan Term Sheet Acknowledgment', 'Funding',
 '2 signers. Non-binding term sheet acknowledgment for a bridge loan. Binding only as to confidentiality/exclusivity if stated.',
 'queued', 820, '2026-08-25T00:00:00.000Z'),
('ttq_083', 'capital-call-notice-ack', 'Capital Call Notice Acknowledgment', 'Funding',
 '2 signers: Fund/Company, Investor. Acknowledge capital call amount and due date.',
 'queued', 830, '2026-08-25T00:00:00.000Z'),
('ttq_084', 'grant-funds-acknowledgment', 'Grant Funds Use Acknowledgment', 'Funding',
 '2 signers: Grantor, Grantee. Acknowledge permitted use of grant funds and reporting.',
 'queued', 840, '2026-08-25T00:00:00.000Z'),
('ttq_085', 'revenue-share-short', 'Short Revenue Share Agreement', 'Funding',
 '2 signers. Simple revenue share % on defined revenue until cap or date.',
 'queued', 850, '2026-08-25T00:00:00.000Z'),
('ttq_086', 'crowdfunding-perk-fulfillment', 'Crowdfunding Perk Fulfillment Acknowledgment', 'Funding',
 '2 signers: Creator, Backer. Acknowledge perk owed and estimated ship date.',
 'queued', 860, '2026-08-25T00:00:00.000Z'),

-- Intellectual Property (8)
('ttq_087', 'copyright-assignment-short', 'Short Copyright Assignment', 'Intellectual Property',
 '2 signers: Assignor, Assignee. Assign copyright in a named work. Moral rights waiver where applicable (plain language).',
 'queued', 870, '2026-08-25T00:00:00.000Z'),
('ttq_088', 'trademark-consent-coexist', 'Trademark Coexistence Consent', 'Intellectual Property',
 '2 signers. Consent to coexist with similar marks in defined fields/territories.',
 'queued', 880, '2026-08-25T00:00:00.000Z'),
('ttq_089', 'open-source-contribution-ack', 'Open Source Contribution Acknowledgment', 'Intellectual Property',
 '1–2 signers: Contributor. CLA-lite: contributions licensed under project license; original work.',
 'queued', 890, '2026-08-25T00:00:00.000Z'),
('ttq_090', 'software-eval-license', 'Software Evaluation License', 'Intellectual Property',
 '2 signers: Vendor, Evaluator. Time-limited eval license, no production use, feedback ownership.',
 'queued', 900, '2026-08-25T00:00:00.000Z'),
('ttq_091', 'content-license-guest-post', 'Guest Content License', 'Intellectual Property',
 '2 signers: Author, Publisher. License to publish guest post; author keeps copyright; portfolio use.',
 'queued', 910, '2026-08-25T00:00:00.000Z'),
('ttq_092', 'invention-disclosure-ack', 'Invention Disclosure Acknowledgment', 'Intellectual Property',
 '2 signers: Employee/Inventor, Company. Acknowledge submission of invention disclosure form.',
 'queued', 920, '2026-08-25T00:00:00.000Z'),
('ttq_093', 'dmca-agent-designation-internal', 'DMCA Agent Designation (Internal)', 'Intellectual Property',
 '1–2 signers. Internal designation of DMCA agent contact for a site. Not a filing form.',
 'queued', 930, '2026-08-25T00:00:00.000Z'),
('ttq_094', 'patent-assignment-short', 'Short Patent Assignment', 'Intellectual Property',
 '2 signers. Assign rights in a patent application/invention described by title. Not legal advice.',
 'queued', 940, '2026-08-25T00:00:00.000Z'),

-- Equity (8)
('ttq_095', 'option-grant-notice-simple', 'Simple Option Grant Notice', 'Equity',
 '2 signers: Company, Optionee. Notice of option grant: shares, strike, vesting start. Plan controls.',
 'queued', 950, '2026-08-25T00:00:00.000Z'),
('ttq_096', 'vesting-acceleration-ack', 'Vesting Acceleration Acknowledgment', 'Equity',
 '2 signers. Acknowledge single/double-trigger acceleration terms summary.',
 'queued', 960, '2026-08-25T00:00:00.000Z'),
('ttq_097', 'equity-repurchase-notice', 'Equity Repurchase Notice Acknowledgment', 'Equity',
 '2 signers. Company exercises repurchase right on unvested shares; price and date.',
 'queued', 970, '2026-08-25T00:00:00.000Z'),
('ttq_098', '83b-election-reminder', '83(b) Election Reminder Acknowledgment', 'Equity',
 '1–2 signers: Recipient. Acknowledge deadline reminder to file 83(b); not tax advice.',
 'queued', 980, '2026-08-25T00:00:00.000Z'),
('ttq_099', 'advisor-equity-grant-notice', 'Advisor Equity Grant Notice', 'Equity',
 '2 signers: Company, Advisor. Shares/% and vesting for advisory role. Cross-ref advisory agreement.',
 'queued', 990, '2026-08-25T00:00:00.000Z'),
('ttq_100', 'share-transfer-restriction-ack', 'Share Transfer Restriction Acknowledgment', 'Equity',
 '2 signers. Stockholder acknowledges ROFR/transfer restrictions under stockholders agreement.',
 'queued', 1000, '2026-08-25T00:00:00.000Z'),

-- Compliance Documents (8)
('ttq_101', 'privacy-policy-ack-employee', 'Employee Privacy Policy Acknowledgment', 'Compliance Documents',
 '1–2 signers: Employee. Acknowledge employer privacy policy for workplace monitoring/data.',
 'queued', 1010, '2026-08-25T00:00:00.000Z'),
('ttq_102', 'acceptable-use-it-ack', 'IT Acceptable Use Policy Acknowledgment', 'Compliance Documents',
 '1 signer: User. Acknowledge IT acceptable use policy.',
 'queued', 1020, '2026-08-25T00:00:00.000Z'),
('ttq_103', 'incident-response-ack', 'Security Incident Reporting Acknowledgment', 'Compliance Documents',
 '1–2 signers. Acknowledge duty to report security incidents promptly.',
 'queued', 1030, '2026-08-25T00:00:00.000Z'),
('ttq_104', 'vendor-security-questionnaire-ack', 'Vendor Security Questionnaire Completion', 'Compliance Documents',
 '2 signers: Vendor, Customer. Acknowledge answers to security questionnaire are accurate.',
 'queued', 1040, '2026-08-25T00:00:00.000Z'),
('ttq_105', 'records-retention-ack', 'Records Retention Policy Acknowledgment', 'Compliance Documents',
 '1 signer. Acknowledge records retention schedule attachment.',
 'queued', 1050, '2026-08-25T00:00:00.000Z'),
('ttq_106', 'anti-bribery-ack', 'Anti-Bribery Policy Acknowledgment', 'Compliance Documents',
 '1–2 signers. Acknowledge anti-bribery/corruption policy.',
 'queued', 1060, '2026-08-25T00:00:00.000Z'),
('ttq_107', 'conflict-of-interest-disclosure', 'Conflict of Interest Disclosure', 'Compliance Documents',
 '1–2 signers. Disclose potential conflicts; management acknowledgment optional.',
 'queued', 1070, '2026-08-25T00:00:00.000Z'),
('ttq_108', 'data-processing-addendum-ack', 'Data Processing Terms Acknowledgment', 'Compliance Documents',
 '2 signers: Controller, Processor. Acknowledge DPA key terms summary (not a full GDPR DPA).',
 'queued', 1080, '2026-08-25T00:00:00.000Z');
`;
