-- Refill the Monday SEO blog queue (lib/blogWeekly.ts). The original 0018 seed (~12 topics)
-- is exhausted after a few Mondays; keep ~3 months of fresh queued angles ready. Slugs must
-- not collide with static ARTICLES / already-published blog_posts rows.
INSERT OR IGNORE INTO blog_topic_queue (id, slug, title, angle, cluster, status, sort_order, created_at) VALUES
('btq_13', 'how-to-sign-a-consulting-agreement-online', 'How to sign a consulting agreement online',
 'Audience: consultants and clients. What belongs in a simple consulting agreement, e-sign without accounts, Docracy steps + free templates. Mistakes (scope creep, IP). FAQ. Soft CTA.',
 'Contract', 'queued', 130, '2026-08-25T00:00:00.000Z'),
('btq_14', 'how-to-collect-signed-offer-letters-remotely', 'How to collect signed offer letters remotely',
 'Audience: small HR / founders hiring remote. Offer letter basics, sequential signing, mobile-friendly links, reminders. Docracy free/paid angles. FAQ. Not employment-law advice.',
 'Small Business', 'queued', 140, '2026-08-25T00:00:00.000Z'),
('btq_15', 'free-nda-template-how-to-send-it', 'Free NDA template: how to send it for signature',
 'Audience: freelancers. Pick a free NDA template, place fields, send, track status. One-way vs mutual. Mistakes + FAQ. CTA to Docracy free templates.',
 'NDA', 'queued', 150, '2026-08-25T00:00:00.000Z'),
('btq_16', 'how-to-sign-documents-on-mobile', 'How to sign documents on mobile without an app',
 'Audience: signers on phones. Browser signing, no app/account, field types, tips for clear signatures. Docracy signer experience. FAQ.',
 'Signing', 'queued', 160, '2026-08-25T00:00:00.000Z'),
('btq_17', 'what-is-a-completion-certificate-esignature', 'What is a completion certificate in e-signature?',
 'Audience: senders who need audit trail. What a completion certificate includes, when it matters, how Docracy emails the PDF + certificate. FAQ. Not legal advice.',
 'Signing', 'queued', 170, '2026-08-25T00:00:00.000Z'),
('btq_18', 'how-to-void-or-cancel-a-pending-signature-request', 'How to void or cancel a pending signature request',
 'Audience: preparers. When to cancel vs remind, how Docracy cancel/void works, what signers see. FAQ.',
 'Signing', 'queued', 180, '2026-08-25T00:00:00.000Z'),
('btq_19', 'sequential-vs-parallel-signing-when-to-use-each', 'Sequential vs parallel signing: when to use each',
 'Audience: ops sending multi-signer docs. Pros/cons, examples (board consents vs NDAs), how to choose in Docracy. FAQ.',
 'Contract', 'queued', 190, '2026-08-25T00:00:00.000Z'),
('btq_20', 'how-to-add-signature-fields-to-a-pdf', 'How to add signature fields to a PDF online',
 'Audience: anyone with a PDF. Field types (signature, initials, date, text, checkbox, dropdown), placement tips, send flow. Docracy prepare UI. FAQ.',
 'Signing', 'queued', 200, '2026-08-25T00:00:00.000Z'),
('btq_21', 'esignature-for-freelancers-getting-paid-faster', 'E-signature for freelancers: getting paid faster',
 'Audience: freelancers. Contracts before work starts, payment terms, reminders, free 2-signer limit honesty. Soft CTA. FAQ.',
 'Freelancer', 'queued', 210, '2026-08-25T00:00:00.000Z'),
('btq_22', 'how-to-send-a-w9-with-an-independent-contractor-agreement', 'How to send a W-9 with an independent contractor agreement',
 'Audience: finance ops. Packet idea ICA+W-9, order of signing, storage. Not tax advice. Docracy templates mention. FAQ.',
 'Freelancer', 'queued', 220, '2026-08-25T00:00:00.000Z'),
('btq_23', 'are-sms-signing-links-secure-enough', 'Are SMS signing links secure enough for contracts?',
 'Audience: US small business. Carrier email-to-SMS caveats, when email is better, PIN option on paid. Honest limits. FAQ.',
 'Signing', 'queued', 230, '2026-08-25T00:00:00.000Z'),
('btq_24', 'how-to-use-anchor-tags-in-pdfs-for-esignature', 'How to use anchor tags in PDFs for e-signature',
 'Audience: power users / templates. {{sig1}} style anchors, dropdowns, when AI detect helps. Paid feature honesty. FAQ.',
 'Contract', 'queued', 240, '2026-08-25T00:00:00.000Z');
