-- Job-door search phrases already routed on /es/buscar:
-- acta de nacimiento apostilla, cita consular AIS, permiso de trabajo I-765, abrir cuenta ITIN.
-- INSERT OR IGNORE so runtime ensureWeekly*Infra and this migration can both run.

INSERT OR IGNORE INTO blog_topic_queue (id, slug, title, angle, cluster, status, sort_order, created_at) VALUES
('btq_37', 'acta-de-nacimiento-apostilla-mexico', 'Acta de nacimiento apostilla: Registro Civil then SRE',
 'Search phrase: acta de nacimiento apostilla / acta México. Step 1 official: https://www.miregistrocivil.gob.mx/ (gob.mx moved new actas here 1 Aug 2025). Step 2 official: https://www.gob.mx/sre/acciones-y-programas/apostilla-y-legalizacion-de-documentos (SRE stamps; we do not). Link /acta and /mexico-to-us. Honest: Docracy signs POA / I-9 / constancia; we do not issue actas or apostille. $10/month keeps the signed extras. FAQ. Not legal advice.',
 'LATAM', 'queued', 370, '2026-09-05T12:00:00.000Z'),
('btq_38', 'cita-consular-ais-cas-ustraveldocs', 'Cita consular AIS / CAS / ustraveldocs — we do not book it',
 'Search phrase: cita consular AIS. Official: https://ais.usvisa-info.com/ (country path chosen on that site). CEAC DS-160 is https://ceac.state.gov/genniv/. Link /consular-appointment. Honest: we do not buy, hold, or reschedule a slot. We sign supporting PDFs (offer, I-9, POA). $10/month vault. FAQ. Not immigration advice.',
 'LATAM', 'queued', 380, '2026-09-05T12:00:00.000Z'),
('btq_39', 'permiso-de-trabajo-i-765-ead-tps', 'Permiso de trabajo I-765 / EAD / TPS — you file, we do not',
 'Search phrase: permiso de trabajo I-765. Official I-765: https://www.uscis.gov/i-765. TPS: https://www.uscis.gov/humanitarian/temporary-protected-status. I-821: https://www.uscis.gov/i-821. Link /ead-tps. Honest: signing ≠ work authorization; no E-Verify; we do not grant TPS or parole. Pair with I-9 we do sign. FAQ. Not legal advice.',
 'Employment', 'queued', 390, '2026-09-05T12:00:00.000Z'),
('btq_40', 'abrir-cuenta-bancaria-con-itin', 'Abrir cuenta with an ITIN: chip first, then the bank',
 'Search phrase: abrir cuenta ITIN. Official ITIN: https://www.irs.gov/tin/itin/how-to-apply-for-an-itin. Bank basics: https://www.consumerfinance.gov/consumer-tools/educator-tools/adult-financial-education/. Link /phone-and-bank and /itin. Honest: we do not sell eSIMs, open accounts, or file W-7. We sign I-9 and a constancia the bank may still reject. FAQ. Not tax or banking advice.',
 'LATAM', 'queued', 400, '2026-09-05T12:00:00.000Z'),
('btq_41', 'apostilla-acta-colombia-cancilleria', 'Colombia acta + Cancillería apostille vs a US I-9',
 'Search phrase: apostilla Colombia / acta Colombia. Official: https://www.cancilleria.gov.co/tramites_servicios/apostilla_legalizacion. Link /colombia-to-us and /acta. Cita consular is AIS, not Cancillería — do not mix. We do not apostille. $10/month packet + vault. FAQ.',
 'LATAM', 'queued', 410, '2026-09-05T12:00:00.000Z'),
('btq_42', 'ds-160-ceac-after-ais-appointment', 'DS-160 on CEAC after you book AIS',
 'Audience: people who typed cita consular then DS-160. Official CEAC: https://ceac.state.gov/genniv/. AIS: https://ais.usvisa-info.com/. Link /consular-appointment. We do not submit DS-160. Supporting docs we sign. FAQ. Not immigration advice.',
 'LATAM', 'queued', 420, '2026-09-05T12:00:00.000Z'),
('btq_43', 'i-9-same-week-as-your-acta-apostille', 'I-9 the same week as your acta apostille — two different jobs',
 'Audience: first-week hires still chasing Registro Civil / SRE. I-9 official: https://www.uscis.gov/i-9. Acta/apostille is origin .gob. Link /i-9 and /acta. Do not wait to sign Section 1. We sign I-9; we do not apostille. FAQ.',
 'Employment', 'queued', 430, '2026-09-05T12:00:00.000Z'),
('btq_44', 'esim-then-itin-then-the-bank', 'eSIM, then ITIN, then the bank (we sell none of these)',
 'Search phrase: chip y banco / abrir cuenta. One-liner: chip first, then the bank. Official CFPB + IRS ITIN links only. Link /phone-and-bank. We do not sell SIMs or open accounts. Soft CTA: $10/month keeps the I-9 and constancia when the bank asks again. FAQ.',
 'LATAM', 'queued', 440, '2026-09-05T12:00:00.000Z');

INSERT OR IGNORE INTO template_topic_queue (id, slug, title, category, angle, status, sort_order, created_at) VALUES
('ttq_119', 'acta-apostille-errand-limited-poa', 'Acta / Apostille Errand Limited Power of Attorney', 'Power of Attorney',
 '2 signers: Principal (in the US), Agent (in origin city). Narrow POA so family can pick up an acta de nacimiento and take it to the origin apostille office. Placeholders: [Principal], [Agent], [City], [Document type]. Honest: Docracy does not issue actas or apostille; Mexico new actas are https://www.miregistrocivil.gob.mx/; SRE apostille is gob.mx/sre. Not legal advice.',
 'queued', 1190, '2026-09-05T12:00:00.000Z'),
('ttq_120', 'consular-ais-document-checklist-ack', 'Consular AIS Appointment Document Checklist Acknowledgment', 'Compliance Documents',
 '1–2 signers: Applicant, optional Helper. Acknowledge they will book cita consular on AIS / CAS / ustraveldocs themselves (https://ais.usvisa-info.com/) and upload DS-160 on CEAC. Not a visa, not a slot reservation. Docracy does not buy or hold appointments. Point to /consular-appointment.',
 'queued', 1200, '2026-09-05T12:00:00.000Z'),
('ttq_121', 'i-765-ead-filing-checklist-ack', 'I-765 / EAD Filing Checklist Acknowledgment', 'Employment',
 '1–2 signers: Applicant, optional Preparer. Acknowledge they will file permiso de trabajo I-765 on USCIS (https://www.uscis.gov/i-765), not here. NOT Form I-765. No E-Verify. Signing ≠ work authorization. TPS/parole: official USCIS pages only. Point to /ead-tps.',
 'queued', 1210, '2026-09-05T12:00:00.000Z'),
('ttq_122', 'itin-bank-account-packet-ack', 'ITIN + Bank Packet Checklist Acknowledgment', 'Compliance Documents',
 '1–2 signers: Applicant, optional Helper. Abrir cuenta ITIN checklist: chip/phone first, then IRS ITIN (https://www.irs.gov/tin/itin/how-to-apply-for-an-itin), then a bank. NOT Form W-7. We do not open accounts or sell eSIMs. Point to /phone-and-bank and /itin.',
 'queued', 1220, '2026-09-05T12:00:00.000Z'),
('ttq_123', 'tps-parole-ead-handoff-ack', 'TPS / Parole / EAD Handoff Acknowledgment', 'Employment',
 '2 signers: Worker, Employer contact. Acknowledge the worker is filing I-765 / I-821 on USCIS and will complete official I-9 separately. Not a work permit. No E-Verify. Official TPS: https://www.uscis.gov/humanitarian/temporary-protected-status.',
 'queued', 1230, '2026-09-05T12:00:00.000Z'),
('ttq_124', 'mexico-registro-civil-sre-handoff-ack', 'Mexico Registro Civil + SRE Handoff Acknowledgment', 'Compliance Documents',
 '2 signers: Person in the US, Family in Mexico. Confirm who pulls the acta on miregistrocivil.gob.mx and who files SRE apostille. We do not apostille. Link /mexico-to-us. Not legal advice.',
 'queued', 1240, '2026-09-05T12:00:00.000Z'),
('ttq_125', 'colombia-cancilleria-apostille-handoff-ack', 'Colombia Cancillería Apostille Handoff Acknowledgment', 'Compliance Documents',
 '2 signers: Person in the US, Family in Colombia. Confirm who files Cancillería apostille/legalización (https://www.cancilleria.gov.co/tramites_servicios/apostilla_legalizacion). Cita consular is AIS, not this. We do not apostille. Link /colombia-to-us.',
 'queued', 1250, '2026-09-05T12:00:00.000Z'),
('ttq_126', 'first-week-i94-and-i9-ack', 'First-Week I-94 and I-9 Acknowledgment', 'Employment',
 '2 signers: New hire, Employer contact. New hire will retrieve I-94 at https://i94.cbp.dhs.gov/I94/#/home and complete official USCIS I-9 Section 1. We do not retrieve I-94. Signing I-9 ≠ work authorization. Point to /after-arrival.',
 'queued', 1260, '2026-09-05T12:00:00.000Z'),
('ttq_127', 'itin-constancia-for-bank-ack', 'ITIN Constancia for Bank Review Acknowledgment', 'Real Estate',
 '2 signers: Applicant, optional Roommate. Bank asked for income proof while ITIN is pending. Constancia / vault URL — not a W-2, not SAT CSF. We do not open the account. Point to /income-proof.',
 'queued', 1270, '2026-09-05T12:00:00.000Z'),
('ttq_128', 'new-us-phone-number-notice', 'New US Phone Number Notice After eSIM', 'Personal Property',
 '1–2 signers: Person, optional Employer/Landlord. Notice of a new US number after getting a chip/eSIM. We do not sell SIMs. Placeholders: [Old number], [New number], [Date]. Point to /phone-and-bank.',
 'queued', 1280, '2026-09-05T12:00:00.000Z');
