/**
 * Legacy docracy.com slug → canonical /free-templates/:slug redirects.
 * Generated by marketing/seo-research/curate-docracy-slugs.mjs — do not edit by hand.
 */
import redirects from "./templateLegacyRedirects.json";

const REDIRECT_MAP: Readonly<Record<string, string>> = redirects;

export function resolveLegacyTemplateSlug(slug: string): string | undefined {
  return REDIRECT_MAP[slug];
}

export function legacyTemplateRedirectTarget(pathname: string): string | null {
  const m = pathname.match(/^\/(?:es\/plantillas-gratis|free-templates)\/([^/]+)\/?$/);
  if (!m) return null;
  const legacy = decodeURIComponent(m[1]);
  const canonical = REDIRECT_MAP[legacy];
  if (!canonical || canonical === legacy) return null;
  const prefix = pathname.startsWith("/es/") ? "/es/plantillas-gratis" : "/free-templates";
  return `${prefix}/${encodeURIComponent(canonical)}`;
}
